#!/usr/bin/make

include Makefile

ifndef UTDATE
	UTARGS := -u 2017
endif

ifndef PROCARGS
	PROCARGS := --nousepixflat --fixsaturation --nobiascorr --noweightmap
endif

DATAINITARGS := $(LOGARGS) $(DATAARGS) $(UTARGS) $(BANDARGS)

INITARGS := $(DATAINITARGS) $(MPARGS) $(VERBOSE)

export SKYFLATARGS := --masterskyflat

