#!/usr/bin/make

all_detrend2014: initproc biasramp badpix proc1 flats proc2

include Makefile

ifndef UTDATE
	UTARGS := -u 201312,2014
endif

ifndef PROCARGS
	PROCARGS := --nousepixflat --rampcorr --noweightmap
endif

INITARGS := $(LOGARGS) $(DATAARGS) $(UTARGS) $(BANDARGS) \
            -p $(NPROC) $(VERBOSE)


# run the pipeline on g-band dark night to look at CCD3 gradient by only doing
# bias subtraction (-n allows comparison of oscan vs. bias-subtracted) with no
# flat-field correction

testgradient_darknight:
	python bokrmpipe.py -u 20140425,20140427 -b g -vvvv -s oscan,bias2d,proc1 \
	                    --noflatcorr --nocombine -n -o $(TESTDIR)

# checking the CCD3 gradient trend over a night where sky goes from 12K to 1K

testgradient_graynight:
	python bokrmpipe.py -u 20140415 -b g -vvvv -s oscan,bias2d,proc1 \
	                    --noflatcorr --nocombine -n -o $(TESTDIR)

# --frames 2635-2640 (starts at 2635 to do a subset)

testgradient_forgnostic:
	python bokrmpipe.py --obsdb config/sdssrm-bok2014.fits \
	                    -u 20140123,20140415,20140427 -b g -vvvv -s proc1 \
	                    --rampcorr --noflatcorr \
	                    --nogainmul --nocombine --nosavegain \
	                    --noweightmap --tmpdirout -R

testfringe:
	python bokrmpipe.py $(INITARGS) \
	                    -s fringe \
	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)

footestfringecont:
	python bokrmpipe.py $(INITARGS) \
	                    -s proc1 --prockey TMPPROC \
	                    --norampcorr --nobiascorr --nosavegain --noweightmap \
	                    --darkskyframes --tmpdirout $(XARGS)
	python bokrmpipe.py $(INITARGS) \
	                    -s proc2 \
	                    --noskyflatcorr --noweightmap \
	                    --skymethod polynomial --skyorder 1 \
	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)
testfringecont:
	python bokrmpipe.py $(INITARGS) \
	                    -s skyflat \
	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)

