#!/usr/bin/make

all_detrend2015: initproc biasramp badpix proc1 flats proc2

include Makefile

ifndef UTDATE
	UTARGS := -u 2015
endif

ifndef PROCARGS
	PROCARGS := --nousepixflat --rampcorr --noweightmap
endif

INITARGS := $(LOGARGS) $(DATAARGS) $(UTARGS) $(BANDARGS) \
            -p $(NPROC) $(VERBOSE)

run1:
	make -f Makefile.2015 all UTDATE=201501

run2:
	make -f Makefile.2015 all UTDATE=201502

