#!/usr/bin/make

all_detrend2015: initproc biasramp badpix proc1 flats proc2

include Makefile

ifndef UTDATE
	UTARGS := -u 2015
endif

ifndef PROCARGS
	PROCARGS := --nousepixflat --rampcorr --noweightmap 
endif

INITARGS := $(LOGARGS) $(DATAARGS) $(UTARGS) $(BANDARGS) \
            $(MPARGS) $(VERBOSE)

# XXX switch fringe to "per-run"

SKYFLATARGS := --masterskyflat

run1flats:
	make -f Makefile flats UTDATE=201501

run2flats:
	make -f Makefile flats UTDATE=201502

run3flats:
	make -f Makefile flats UTDATE=201503

run4flats:
	make -f Makefile flats UTDATE=201504

run5flats:
	make -f Makefile flats UTDATE=2015050

run6flats:
	make -f Makefile flats UTDATE=2015052

run7flats:
	make -f Makefile flats UTDATE=201507

allflats: run1flats run2flats run3flats run4flats \
          run5flats run6flats run7flats

