#!/usr/bin/make

.PHONY: initproc badpix flats finalproc proc redo

TOOLS := $(HOME)/dev/rapala/bokpipe/tools

ifdef LOGFILE
	LOGARGS := --obsdb $(LOGFILE)
else
	LOGARGS := --obsdb config/sdssrm-bok2014.fits
endif

ifdef RAWDATA
	DATAARGS := -r $(RAWDATA)
endif

ifdef UTDATE
	UTARGS := -u $(UTDATE)
endif

ifndef NPROC
	NPROC := 7
endif

ifndef VERBOSE
	VERBOSE := -vvvv
endif

ifdef BANDS
	BANDARGS := -b $(BANDS)
endif

ifndef PROCARGS
	PROCARGS := --nousepixflat --rampcorr
#	PROCARGS := --nousepixflat --fixsaturation --nobiascorr # XXX 2016 data
endif

INITARGS := $(LOGARGS) $(DATAARGS) $(UTARGS) $(BANDARGS) \
            -p $(NPROC) $(VERBOSE)

all: initproc badpix flats finalproc

initproc:
	python bokrmpipe.py $(INITARGS) $(PROCARGS) \
	                    -s oscan,bias2d,flat2d,ramp \
	                    -vvv $(XARGS)

# XXX copy in a master bp mask from config dir
badpix:
	cp $(BOK90PRIMEOUTDIR)/bokpipe_v0.2/cals/BadPix* $(BOK90PRIMEOUTDIR)/bokpipe_v0.3/cals/

#	python bokrmpipe.py $(INITARGS) \
#	                    -s bpmask -u 20140425 -b g $(XARGS)

#flats_proc1:
#	python bokrmpipe.py $(INITARGS) \
#	                    -s proc1 --prockey TMPPRO1 \
#	                    --nobiascorr --nosavegain --noweightmap \
#	                    --darkskyframes --tmpdirout $(XARGS)

proc1:
	python bokrmpipe.py $(INITARGS) $(PROCARGS) \
	                    -s proc1 \
	                    -vvv $(XARGS)

flats_makeillum:
	python bokrmpipe.py $(INITARGS) \
	                    -s illum \
	                    --darkskyframes $(XARGS)

flats_illumcorr:
	python bokrmpipe.py $(INITARGS) \
	                    -s proc2 --prockey TMPPRO2 \
	                    --nofringecorr --noskyflatcorr \
	                    --noskysub --noweightmap \
	                    --darkskyframes --tmpdirout $(XARGS)
#	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)

flats_makefringe:
	python bokrmpipe.py $(INITARGS) \
	                    -s fringe \
	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)

flats_fringeskycorr:
	python bokrmpipe.py $(INITARGS) \
	                    -s proc2 --prockey TMPPRO3 \
	                    --noillumcorr --noskyflatcorr --noweightmap \
	                    --skymethod polynomial --skyorder 1 \
	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)

flats_makeskyflat:
	python bokrmpipe.py $(INITARGS) \
	                    -s skyflat \
	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)

#flats_proc1 \
#       flats_makeillum flats_illumcorr \
#

flats: flats_makeillum flats_illumcorr \
       flats_makefringe flats_fringeskycorr \
       flats_makeskyflat

finalproc:
	python bokrmpipe.py $(INITARGS) $(PROCARGS) \
	                    -s proc1,proc2 \
	                    $(XARGS)

procall:
	python bokrmpipe.py $(INITARGS) $(PROCARGS) \
	                    -s oscan,proc1,proc2 \
	                    $(XARGS)

catalogs:
	python bokrmpipe.py $(INITARGS) -s wcs,cat $(XARGS)

redo:
	make -f Makefile.2014 XARGS="-R $(XARGS) -t object" procall catalogs

steps:
	python bokrmpipe.py $(INITARGS) $(PROCARGS) -s $(STEPS) $(XARGS)

images:
	python bokrmpipe.py $(INITARGS) --images $(XARGS)

# run the pipeline on g-band dark night to look at CCD3 gradient by only doing
# bias subtraction (-n allows comparison of oscan vs. bias-subtracted) with no
# flat-field correction

testgradient_darknight:
	python bokrmpipe.py -u 20140425,20140427 -b g -vvvv -s oscan,bias2d,proc1 \
	                    --noflatcorr --nocombine -n -o $(TESTDIR)

# checking the CCD3 gradient trend over a night where sky goes from 12K to 1K

testgradient_graynight:
	python bokrmpipe.py -u 20140415 -b g -vvvv -s oscan,bias2d,proc1 \
	                    --noflatcorr --nocombine -n -o $(TESTDIR)

testgradient_forgnostic:
	python bokrmpipe.py --obsdb config/sdssrm-bok2014.fits \
	                    -u 20140123,20140415,20140427 -b g -vvvv -s proc1 \
	                    --rampcorr --noflatcorr \
	                    --nogainmul --nocombine --nosavegain \
	                    --noweightmap --tmpdirout -R

testfringe:
	python bokrmpipe.py $(INITARGS) \
	                    -s fringe \
	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)

footestfringecont:
	python bokrmpipe.py $(INITARGS) \
	                    -s proc1 --prockey TMPPROC \
	                    --norampcorr --nobiascorr --nosavegain --noweightmap \
	                    --darkskyframes --tmpdirout $(XARGS)
	python bokrmpipe.py $(INITARGS) \
	                    -s proc2 \
	                    --noskyflatcorr --noweightmap \
	                    --skymethod polynomial --skyorder 1 \
	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)
testfringecont:
	python bokrmpipe.py $(INITARGS) \
	                    -s skyflat \
	                    --darkskyframes --tmpdirin --tmpdirout $(XARGS)

