#!/usr/bin/make

include Makefile

ifndef UTDATE
	UTARGS := -u 2016
endif

ifndef PROCARGS
	PROCARGS := --nousepixflat --fixsaturation --nobiascorr --noweightmap \
	            --noskyflatcorr
endif

INITARGS := $(LOGARGS) $(DATAARGS) $(UTARGS) $(BANDARGS) \
            $(MPARGS) $(VERBOSE)

