#!/usr/bin/make

all_detrend2015: initproc biasramp badpix proc1 flats proc2

include Makefile

ifndef UTDATE
	UTARGS := -u 2015
endif

ifndef PROCARGS
	PROCARGS := --nousepixflat --rampcorr --noweightmap 
endif

INITARGS := $(LOGARGS) $(DATAARGS) $(UTARGS) $(BANDARGS) \
            $(MPARGS) $(VERBOSE)

# XXX switch fringe to "per-run"

export SKYFLATARGS := --masterskyflat

flats15:
	for utd in 201501 201502 201503 201504 2015050 2015052 201507; do \
		make -f Makefile flats UTDATE=$$utd; \
	done

